### PR TITLE
Extended Economics & CCUS Profiles

### PR DESCRIPTION
**Pull request by softwareengineerprogrammer**
Addresses:
* https://github.com/NREL/python-geophires-x/issues/71
* https://github.com/NREL/python-geophires-x/issues/70

Enables rendering profiles in UI as implemented in https://github.com/softwareengineerprogrammer/geothermal-ui/compare/1075b88a7754b160129fc34a7c0be02831f4483f..9a3dd83b0aab252fa9a15807b5b30224fdc957bb:

Screenshot 2023-12-08 at 12 12 24

Includes other fixes/improvements such as parsing power plant type, design, and fluid.

### CODE REVIEW

**Review by malcolm-dsider — APPROVED** [review]
Looks good. While testing in the webUI, I discovered a useful trick we probably should publicize- If you select the results in a browser, including the figures at the bottom, copy the results to the clipboard, then paste them into a text editor, you get the results as text, including the table of the data behind the graph (and not the graph itself, which is OK). I have been wanting a way to get the raw table data from the results in the webUI, and now I have it!

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider thanks for the approval!

Interesting finding about the copy-pasteability of the graphs, I actually did not know that! (I guess it must be a feature of Google Charts - the web UI is my first time using them.) I am currently working on an option to download results as CSV - I added CSV generation in https://github.com/NREL/python-geophires-x/pull/73 and just need to integrate it into the UI. Will let you know when it's available.

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider Added CSV download to the UI (https://github.com/softwareengineerprogrammer/geothermal-ui/commit/8ba972641fbd74d020328f652875bbbc618ef52f), give it a whirl and let me know what you think.

image

**Comment by malcolm-dsider** [comment]
Looks good. My only concern is the size of the font for the “link” and “csv” – hard to read, easy to miss…

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider thanks for the feedback, increased the font size a bit

**Pull request merged**
