### PR TITLE
Reference Manual (Parameters) + README cleanup

### PR DESCRIPTION
**Pull request by softwareengineerprogrammer**
## Summary of changes

This PR adds the "GEOPHIRES-X Reference Manual" to support autogenerated parameters documentation. My fork's version is available at https://softwareengineerprogrammer.github.io/python-geophires-x-nrel/parameters.html for review.

Technical details:

* Updated the schema generator to output RST in addition to JSON ([code](https://github.com/softwareengineerprogrammer/python-geophires-x-nrel/blob/a244c48516a5775df96ab58f32f7c0be41e9a206/src/geophires_x_schema_generator/main.py#L14-L107))
* Added a step in the tox docs environment to generate that RST prior to the sphinx build ([code](https://github.com/softwareengineerprogrammer/python-geophires-x-nrel/blob/a244c48516a5775df96ab58f32f7c0be41e9a206/tox.ini#L63)).
* Enabled Sphinx docs 
* Added a GitHub action that uploads the sphinx docs build to GitHub pages ([code](https://github.com/softwareengineerprogrammer/python-geophires-x-nrel/blob/a244c48516a5775df96ab58f32f7c0be41e9a206/.github/workflows/github-actions.yml#L125-L168))

Additionally, I made updates to the README/documentation:
* Added link to web interface
* Incorporated references to the Reference Manual where appropriate
* Added code examples to Usages
* Restructured sections/content to be more coherent/user-friendly

Preview README at https://github.com/softwareengineerprogrammer/python-geophires-x-nrel/blob/main/README.rst

## FAQ

**Q: Why didn't I port all documentation (instead of just the Parameters Reference) to Sphinx/GitHub Pages?**

This was my original plan once I had validated that I was able to generate Sphinx docs and deploy them to Pages using Actions. However, a number of factors arose that led to the split approach in this PR:
1. This was my first time using RST in any serious capacity and I experienced an unexpectedly steep learning curve implementing basic documentation features such as hyperlinks and inter/intra-document references. In many cases I was either unable to figure out how to structure/format documents in a functional and acceptable way, or the syntax was so esoteric and complex that I did not feel it would be practically maintainable by myself or other collaborators.
2. GitHub's default rendering of READMEs is a good UX that is familiar to many developers and lower-friction than having to click a link to go to a separate documentation site. I hadn't fully appreciated this until I experimented with replacing the existing README with a link to the Pages-hosted docs in my own repo. Thus I believe it makes sense to maintain README.rst as the entry point to documentation for the time-being.

---

## Merge criteria:

- [x] Review documentation updates with @malcolm-dsider and @kfbeckers 
- [x] @kfbeckers (or other NREL repo admin) enable GitHub pages (see [relevant comment](https://github.com/NREL/python-geophires-x/pull/26#issuecomment-1786042932))
- [x] Confirm having tinyurl.com/geophires link in README is acceptable to NREL

### CODE REVIEW

**Comment by softwareengineerprogrammer** [comment]
Note that failure of https://github.com/NREL/python-geophires-x/actions/runs/6698182557/job/18201221594 is expected until NREL GitHub admin enables repo GitHub pages

**Comment by softwareengineerprogrammer** [comment]
@kfbeckers this PR includes a link to the web interface (tinyurl.com/geophires) in the README. Is NREL ok with having this link in the repository?

**Comment by kfbeckers** [comment]
Yes, that should be no problem.

Regards,
Koenraad

**Comment by malcolm-dsider** [comment]
I think this is a great start, but I think the input and output parameters are best broken down into groups based on the object they come from. Right now, they are all lumped together. I'd like to see the Reservoir object parameters together, the Wellbores parameters together, etc. I think that makes them easier to understand and find.

Also, I prefer the doc-style format of the attached file. [GitHub prevents me from attaching an HTML file, so take this file and change the extension back to .HTML from .txt]. I like this format because it consolidates the parameter lists along with functions and methods documentation.

[ILikeThis.txt](https://github.com/NREL/python-geophires-x/files/13221200/ILikeThis.txt)

**Comment by softwareengineerprogrammer** [comment]
> I think this is a great start, but I think the input and output parameters are best broken down into groups based on the object they come from. Right now, they are all lumped together. I'd like to see the Reservoir object parameters together, the Wellbores parameters together, etc. I think that makes them easier to understand and find.
> 
> Also, I prefer the doc-style format of the attached file. [GitHub prevents me from attaching an HTML file, so take this file and change the extension back to .HTML from .txt]. I like this format because it consolidates the parameter lists along with functions and methods documentation.
> 
> [ILikeThis.txt](https://github.com/NREL/python-geophires-x/files/13221200/ILikeThis.txt)

Thanks for the feedback @malcolm-dsider. Some amount of categorization is probably practical to get in this PR. Full-on pydoc style probably won't be but I'll see if there's any low-hanging fruit to move in that direction.

**Comment by malcolm-dsider** [comment]
Maybe we could have a look at what I did with Sphinx as a starting point...


________________________________

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider Understand the rationale for wanting to reference/structure according to the corresponding modules and I did in fact spend many hours exploring with that concept, but due to various complexities/complications I estimate it would take me possibly 2+ weeks of full-time work to make that happen in a way that would be functionally superior to where things are at now - the main time sucks being cleanup of the existing doc strings, significant refactoring of parameter typing/consumption, and either making the source self-modifying to update its own docstrings or some kind of build-step equivalent thereof. This change does in fact include Sphinx docs of relevant classes which you can see at https://softwareengineerprogrammer.github.io/python-geophires-x-nrel/reference/geophires_x.html#module-geophires_x, but I decided to keep it 'hidden' (i.e. not explicitly linked from sidebar or otherwise referenced aside from the Sphinx template modules link in the footer) because it exposes some of the aforementioned docstring issues.

I broke the input parameters table into categories for now to improve organization and at least give a general idea of where to look for a given parameter in code - see https://softwareengineerprogrammer.github.io/python-geophires-x-nrel/parameters.html.

With that context in mind - are you OK merging in as-is for now given it represents a substantial improvement over the status quo, even if we recognize it's limited and would like to significantly improve when time/resources permit?

**Comment by malcolm-dsider** [comment]
Jonathan – 

 

I am okay with merging the work you have already done into production, as it represents a substantial improvement on what we have now, and it is likely to be the basis for whatever we do going forward.

 

About the time sucks mentioned below – “cleanup of the existing doc strings, significant refactoring of parameter typing/consumption, and either making the source self-modifying to update its own docstrings or some kind of build-step equivalent thereof”- I think that I (and maybe Koenraad) would handle the cleanup/improvement of the docstrings. Also, I had in mind a program we could add to the build step that regenerates the parameter tables in the docstrings of the key objects on-the-fly based on the parameters. So perhaps by combining our efforts, we can reduce your overall effort, but I am not sure what “significant refactoring of parameter typing/consumption” and what level of effort that entails.

 

Let’s talk it through during our call today.

 

I also suggest we discuss if there is a platform we should use for discussions like Koenraad is having with Sam Klarin. Email is okay, but it is a 1-1 transfer of information. What happens next time someone has questions similar to Sam’s? Do we have the conversation again? It seems to me that the discussion should go into some forum that can be referred to for future reference. Is that GitHub? Reddit? 

 

-Malcolm

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider awesome, glad we're in agreement it makes sense to merge now and iteratively improve afterwards. Will merge today.

> I think that I (and maybe Koenraad) would handle the cleanup/improvement of the docstrings.

Great, I was going to suggest that you 2 are better suited to handle this than I content-wise - let's just make sure we discuss technical aspects beforehand (such as on the call today) to avoid potential issues 

> Also, I had in mind a program we could add to the build step that regenerates the parameter tables in the docstrings of the key objects on-the-fly based on the parameters.

Yes, sounds like we have similar ideas about this - this is roughly what I was referring to with "making the source self-modifying to update its own docstrings or some kind of build-step equivalent thereof" (“significant refactoring of parameter typing/consumption” being a key aspect of how I would approach implementation thereof).

**Comment by softwareengineerprogrammer** [comment]
Note: added follow-up commit outside of this PR which switches references to my fork's docs deployment to https://nrel.github.io/python-geophires-x: https://github.com/NREL/python-geophires-x/commit/93e675c36246589471a99d6b468d89ba86332862

**Pull request merged**
